"""add category_id to brands

Revision ID: 05c839eed59d
Revises: 8b6cc373839d
Create Date: 2026-08-17 11:48:24.675221
"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '05c839eed59d'
down_revision: Union[str, None] = '8b6cc373839d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'audit_logs',
        existing_comment='Append-only audit trail. UPDATE and DELETE are blocked by PostgreSQL rules. Records are immutable once created.',
        schema=None
    )
    op.add_column('brands', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_brands_category_id'), 'brands', ['category_id'], unique=False)
    op.create_foreign_key(None, 'brands', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'brands', type_='foreignkey')
    op.drop_index(op.f('ix_brands_category_id'), table_name='brands')
    op.drop_column('brands', 'category_id')
    op.create_table_comment(
        'audit_logs',
        'Append-only audit trail. UPDATE and DELETE are blocked by PostgreSQL rules. Records are immutable once created.',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###
